agente_atendimento_task:
  description: >
    Realizar atendimento consultivo e qualificado a médicos interessados em organização financeira e investimentos.
      
      Você deve:
      1. Conduzir uma conversa natural seguindo o fluxo estabelecido
      2. Identificar se o médico atua como PJ (foco principal)
      3. Explorar dores relacionadas a organização financeira e proteção
      4. Coletar informações de qualificação de forma não invasiva
      5. Direcionar para contato com assessor quando apropriado
      6. Manter registro das informações coletadas para posterior uso
      
      IMPORTANTE: Sempre priorize a experiência do usuário e construção de confiança 
      sobre pressão comercial. Um lead bem qualificado vale mais que vários mal qualificados.
  expected_output: >
      Um relatório estruturado contendo:
      - Status da conversa (Em andamento/Finalizada/Transferida)
      - Perfil identificado (PJ/CLT/Ambos/Não qualificado)
      - Informações coletadas:
        * Faixa de renda (se fornecida)
        * Situação atual de poupança
        * Reserva de emergência
        * Principal objetivo financeiro
        * Dados de contato (se autorizados)
      - Próximos passos recomendados
      - Nível de interesse demonstrado (Alto/Médio/Baixo/Nenhum)
      - Observações relevantes sobre a conversa
  agent: agente_atendimento

agente_qa_task:
  description: >
      Processar a seguinte pergunta: 
      {question} - 
      
      responda sobre investimentos ou planejamento financeiro usando a base RAG como fonte principal.
      
      Processo obrigatório:
      1. **Analisar a pergunta** e identificar palavras-chave e tema principal
      2. **Consultar base RAG** usando a ferramenta JSONSearchTool com palavras-chave específicas
      3. **Extrair informações relevantes** da base de perguntas e respostas
      4. **Estruturar resposta completa** combinando múltiplas fontes se necessário
      5. **Adaptar linguagem** para o perfil específico de médicos PJ
      6. **Incluir disclaimers** apropriados conforme tipo de informação
      7. **Sugerir próximos passos** quando aplicável
      
      IMPORTANTE: Use a ferramenta JSONSearchTool passando apenas uma string de busca simples como parâmetro search_query.
      Exemplo: se a pergunta for sobre investimentos, use search_query="investimentos" ou "como investir".
      
      Critérios de qualidade:
      - Resposta deve ser 100% baseada na base RAG
      - Linguagem clara e didática
      - Contextualizada para médicos PJ
      - Inclui exemplos práticos quando disponíveis
      - Tem disclaimers de compliance quando necessário
      
      Se a informação não estiver disponível na base RAG:
      - Seja transparente sobre a limitação
      - Ofereça buscar com equipe especializada
      - Sugira contato direto com assessor
      - Nunca invente ou assuma informações
  expected_output: >
      Resposta estruturada contendo: Resposta direta e clara à pergunta, baseada exclusivamente no RAG
  agent: agente_qa


agente_principal_task:
    description: >
      Ser o primeiro contato acolhedor com o usuário, respondendo diretamente quando possível 
      ou direcionando para agentes especializados quando necessário conhecimento técnico ou comercial avançado.

      Pergunta do usuário: {question}
      
      Processo de análise obrigatório:
      
      1. **ANÁLISE DA MENSAGEM**:
         - Identificar se é uma interação básica (saudação, conversa casual)
         - Classificar nível de complexidade (básico/intermediário/avançado)
         - Avaliar se demonstra interesse comercial claro
      
      2. **DECISÃO DE AÇÃO**:
         - RESPONDER DIRETAMENTE: Para interações básicas, saudações, esclarecimentos simples
         - DELEGAR: Para questões técnicas complexas ou interesse comercial estruturado
      
      3. **EXECUÇÃO DA RESPOSTA**:
         - Se resposta direta: Fornecer resposta acolhedora e natural
         - Se delegação: Escolher agente adequado e justificar decisão
      
      4. **PRESERVAÇÃO DO CONTEXTO**:
         - Manter histórico de todas as interações
         - Garantir continuidade entre respostas diretas e delegações
      
      **Prioridades**:
      1. Construir rapport e confiança com o usuário
      2. Responder diretamente sempre que possível
      3. Delegar apenas quando necessário expertise específica
      4. Manter experiência fluida e humanizada
      
      **Situações especiais**:
      - Usuários confusos: Responder diretamente com orientação
      - Transições entre agentes: Fazer de forma suave e explicativa
      - Conversas casuais: Manter engajamento sem forçar direcionamento comercial
    
    expected_output: >
      Resposta estruturada que pode ser uma resposta direta ou uma delegação:

      Resposta natural, acolhedora e personalizada para médicos PJ
    agent: agente_principal