agente_orquestrador_task:
  description: >
    Analisar a pergunta do usuário e responder de forma adequada.
    
    Pergunta do usuário: {question}
    
    Você deve analisar a pergunta e tomar uma das seguintes ações:
    
    1. **Para cumprimentos simples** (olá, oi, tudo bem, como vai):
       - Responda diretamente de forma acolhedora
       - Apresente brevemente os serviços disponíveis
    
    2. **Para perguntas sobre investimentos, planejamento financeiro, produtos financeiros**:
       - Use "Ask question to coworker"
       - coworker: "Especialista em Respostas Financeiras"
       - question: a pergunta completa do usuário
       - context: "O usuário está perguntando sobre investimentos/finanças. Responda baseado na base de conhecimento RAG."
    
    3. **Para solicitações de atendimento, consultoria, qualificação de perfil**:
       - Use "Ask question to coworker"
       - coworker: "Assistente de Atendimento"
       - question: a solicitação completa do usuário
       - context: "O usuário precisa de atendimento consultivo. Conduza uma conversa qualificada."
    
    4. **Para apresentação de serviços, primeiros contatos**:
       - Use "Ask question to coworker"
       - coworker: "Recepcionista Virtual Inteligente"
       - question: a mensagem do usuário
       - context: "O usuário está fazendo primeiro contato. Recepcione de forma acolhedora."
    
    IMPORTANTE: 
    - Use EXATAMENTE os nomes dos coworkers como listados acima
    - Sempre inclua contexto completo
    - Para cumprimentos simples, responda diretamente sem usar ferramentas
  
  expected_output: >
    Resposta completa e personalizada para a pergunta do usuário.

agente_atendimento_task:
  description: >
    Realizar atendimento consultivo e qualificado a médicos interessados em organização financeira e investimentos.
      
      Você deve:
      1. Conduzir uma conversa natural seguindo o fluxo estabelecido
      2. Explorar dores relacionadas a organização financeira e proteção
      3. Coletar informações de qualificação de forma não invasiva
      4. Direcionar para contato com assessor quando apropriado
      5. Manter registro das informações coletadas para posterior uso
      
      IMPORTANTE: Sempre priorize a experiência do usuário e construção de confiança 
      sobre pressão comercial. Um lead bem qualificado vale mais que vários mal qualificados.
  expected_output: >
      Um relatório estruturado contendo:
      - Status da conversa (Em andamento/Finalizada/Transferida)
      - Perfil identificado (PJ/CLT/Ambos/Não qualificado)
      - Informações coletadas:
        * Faixa de renda (se fornecida)
        * Situação atual de poupança
        * Reserva de emergência
        * Principal objetivo financeiro
        * Dados de contato (se autorizados)
      - Próximos passos recomendados
      - Nível de interesse demonstrado (Alto/Médio/Baixo/Nenhum)
      - Observações relevantes sobre a conversa

agente_qa_task:
  description: >
      Processar a seguinte pergunta: 
      {question} - 
      
      responda sobre investimentos ou planejamento financeiro usando a base RAG como fonte principal.
      
      Processo obrigatório:
      1. **Analisar a pergunta** e identificar palavras-chave e tema principal
      2. **Consultar base RAG** usando a ferramenta JSONSearchTool com palavras-chave específicas
      3. **Extrair informações relevantes** da base de perguntas e respostas
      4. **Estruturar resposta completa** combinando múltiplas fontes se necessário
      5. **Adaptar linguagem** para o perfil específico
      6. **Incluir disclaimers** apropriados conforme tipo de informação
      7. **Sugerir próximos passos** quando aplicável
      
      IMPORTANTE: Use a ferramenta JSONSearchTool passando apenas uma string de busca simples como parâmetro search_query.
      Exemplo: se a pergunta for sobre investimentos, use search_query="investimentos" ou "como investir".
      
      Critérios de qualidade:
      - Resposta deve ser 100% baseada na base RAG
      - Linguagem clara e didática
      - Inclui exemplos práticos quando disponíveis
      - Tem disclaimers de compliance quando necessário
      
      Se a informação não estiver disponível na base RAG:
      - Seja transparente sobre a limitação
      - Ofereça buscar com equipe especializada
      - Sugira contato direto com assessor
      - Nunca invente ou assuma informações
  expected_output: >
      Resposta estruturada contendo: Resposta direta e clara à pergunta, baseada exclusivamente no RAG

agente_recepcionista_task:
  description: >
    Recepcionar o usuário e coletar informações iniciais para direcionamento adequado.
    
    Processo:
    1. **Saudar o usuário** de forma amigável e acolhedora
    2. **Coletar informações básicas** como nome, profissão e interesse principal
  expected_output: >
      Resposta estruturada contendo:
      - Nome do usuário
      - Profissão
      - Interesse principal (ex: organização financeira, investimentos, aposentadoria)
      - Qualquer informação adicional relevante coletada