[project]
name = "demo_bot"
version = "0.1.0"
description = "demo-bot using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.148.0,<1.0.0",
    "streamlit>=1.28.0",
]

[project.scripts]
demo_bot = "demo_bot.main:run"
run_crew = "demo_bot.main:run"
train = "demo_bot.main:train"
replay = "demo_bot.main:replay"
test = "demo_bot.main:test"
ui = "demo_bot.run_ui:run_streamlit"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
